### ISSUE TITLE
Not saving when it should be?

### ISSUE THREAD

**Issue by Owen7000** [SebLague/Digital-Logic-Sim#97]
Hi there.

Throughout today I have been playing around with DLS.
I had stopped to get something for lunch, so I had closed the app.
I have now come back from lunch to find that almost five hours worth of work has been erased. I believe that this could have been prevented if we were provided with some indication as to whether or not things have been saved recently. Or, some way for us to save it ourselves. I am running the app on Windows Ten.

I am really devastated because as I said, I've lost over five hours worth of work but I would more like to get this added so that nobody else has to go through the same experience.

Thanks.

**Comment by SebLague** [comment]
Hi Owen, I'm very sorry that you lost so much work. The app currently only saves a design once you press the 'create' button and give the chip a name, but I agree that it should save your current work-in-progress if you exit before that as well.

If you're having an issue where chips that you had actually named and created are not loading in, then please let me know, because that could just be a loading bug, in which case it might be possible for them to be restored.

**Comment by SebLague** [comment]
That's strange! I can maybe figure out what's gone wrong if you wouldn't mind sending me your save file. You can find it by navigating on your harddrive to Users>username>AppData>LocalLow>Sebastian Lague>Digital Logic Sim. There should be a folder in there called SaveData which you can email to me at sebastlagueb@gmail.com

**Comment by SebLague** [comment]
Thanks for sending the files. There's clearly some bugs in my saving system because there were a few things that didn't make sense in the data. For example, some chips that use the bus you made list it as having 8 input pins instead of 16. Also the build order got messed up somehow, so it was trying to load some chips in before their component chips had been loaded.

I'm planning on doing a total rewrite and redesign of this project at some point in the future, but as an attempted work-around for now I've updated the windows build on itch.io with a patch that fixes the build order, and ignores pins that are missing in the save file (instead of failing the load). Unless these pins were unused by the parent chip, this will likely cause some of the functionality to break, but I hope that at least the majority are working. It would be great if you could give it a try sometime and let me know! (The new build should say version 0.26 in the bottom right).

**Comment by Owen7000** [comment]
HI, I'll give the new ve4rsion a go now!

**Comment by Owen7000** [comment]
Hi again...
It's done it again...
It appears to be the exact same issue. 
The chips are in the savedata file but again they don't show up in the app.

**Comment by SebLague** [comment]
Hey, I'm happy to hear it seems to be working. I got an email notification from github that you'd commented about the issue returning, but I don't see the message here. I assume you deleted it, but just wanted to confirm if it's still working or if I should try debugging it some more?

**Comment by Owen7000** [comment]
Hiya!
Yeah, I accidentally closed the app and then opened it again. Didn't realise that the chips reordered into alphabetical when you re-open the project so I'd put the message up, then realised haha
Everything seems to be working fine!

**Comment by Owen7000** [comment]
I think it's a good thing, keeps everything organised!
It's maybe something that you could add in the next version, a sort of grouping system for chips?
Thanks for your amazing help, I honestly don't know what I would have done without it 😅😂
